spring.jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
application:
  dataServiceCatalogsUri: ${FDK_DATASERVICE_HARVESTER_URI:https://dataservices.staging.fellesdatakatalog.digdir.no}/catalogs
  namespace: ${NAMESPACE:staging}
  fdkDataServiceUri: ${FDK_DATASERVICE_HARVESTER_URI:https://staging.fellesdatakatalog.digdir.no}/dataservices
server.port: 8080

---
spring:
  profiles: contract-test
application:
  dataServiceCatalogsUri: http://localhost:5000/catalogs
