spring.jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server.port: 8080

---
spring:
  profiles: develop

---
spring:
  profiles: contract-test
server.port: 5050
